const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
function load(name) { const ctx=vm.createContext(name==='Model'?{I18n:load('I18n')}:{}); vm.runInContext(fs.readFileSync(`${__dirname}/../neural.crypto/${name}.js`,'utf8').replace('.pragma library','').replace('.import "I18n.js" as I18n',''),ctx);return ctx; }
const m=load('Model');
const legacy={id:'bitcoin|above|100000.00000000',coin:'bitcoin',vs:'usd',dir:'above',price:100000,armed:true};
let alerts=m.normalizedAlerts([legacy,{...legacy,vs:'brl'}]);
assert.equal(alerts.length,2,'legacy currency collision must migrate to distinct IDs');
assert.notEqual(alerts[0].id,alerts[1].id);
assert.notEqual(m.alertId('aero','above',1e-10,'usd'),m.alertId('aero','above',2e-10,'usd'));
const first=alerts[0].id;
alerts=m.toggleAlert(alerts,first);assert.equal(alerts[0].armed,false);assert.equal(alerts[0].paused,true);
alerts=m.replaceAlert(alerts,{...alerts[0],price:110000},first);
assert.equal(alerts.length,2);assert.equal(alerts[1].price,110000);assert.equal(alerts[1].paused,true);assert.equal(alerts[1].vs,'usd');
alerts=m.toggleAlert(alerts,alerts[1].id);assert.equal(alerts[1].armed,true);assert.equal(alerts[1].paused,false);
assert.equal(m.parseLocalNumber('1e-8'),1e-8);
const fired=m.normalizedAlerts([{...legacy,armed:false,firedAt:Date.now(),firedPrice:100001}]);
assert.equal(fired[0].paused,false);assert.equal(m.toggleAlert(fired,fired[0].id)[0].firedAt,0);
const c=load('Cache'), at=Date.now();
assert.equal(c.restore('{broken'),false);
assert.equal(c.restore('{"version":999,"buckets":{}}'),false);
assert.equal(c.put('sparks','BTCUSDT',{at:at-8*86400000,values:[1,2]}),false);
assert.equal(c.put('sparks','BTCUSDT',{at:at+120000,values:[1,2]}),false);
assert.equal(c.put('sparks','BTCUSDT',{at,values:[1,NaN]}),false);
assert.equal(c.put('quotes','quotes-key',{at,prices:{bitcoin:{usd:{price:100,change:2},brl:{price:500,change:2}}}}),true);
assert.equal(c.put('sparks','BTCUSDT',{at,values:[1,2,3]}),true);
const candles=Array.from({length:900},(_,i)=>({t:i+1,o:2,h:3,l:1,c:2,v:5}));
assert.equal(c.put('charts','BTCUSDT:1h',{at,candles,start:800,end:900,ended:true}),true);
const doc=c.snapshot(), cold=load('Cache');
assert.equal(cold.restore(doc),true);
assert.equal(cold.get('quotes','quotes-key').prices.bitcoin.usd.price,100);
assert.equal(cold.get('sparks','BTCUSDT').values.length,3);
assert.equal(cold.get('charts','BTCUSDT:1h').candles.length,720);
assert.equal(cold.get('charts','BTCUSDT:1h').start,620);
assert.equal(cold.get('charts','BTCUSDT:1h').ended,false);
cold.put('sparks','BTCUSDT',{at:at+1,values:[4,5]});cold.restore(doc);
assert.equal(cold.get('sparks','BTCUSDT').values[0],4,'late disk read cannot overwrite live data');
for(let i=0;i<40;i++)cold.put('sparks','pair'+i,{at:at+i,values:[1,2]});
assert.equal(Object.keys(cold.entries('sparks')).length,24);
assert.equal(cold.put('sparks','__proto__',{at,values:[1,2]}),false);
const ownerA={},ownerB={};assert.equal(cold.claim(ownerA),true);assert.equal(cold.claim(ownerB),false);cold.release(ownerA);assert.equal(cold.claim(ownerB),true);
assert.equal(cold.dirty(),true);cold.saved(cold.revision);assert.equal(cold.dirty(),false);
console.log('State: alert migration/edit/pause/resume, disk roundtrip, corruption/age validation, bounded cache, late-load race and single writer passed');
