const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const i18n = vm.createContext({});
vm.runInContext(fs.readFileSync(`${__dirname}/../rafa.crypto/I18n.js`, 'utf8').replace('.pragma library','').replace('.import "I18n.js" as I18n',''), i18n);
i18n.localeOverride='pt_BR';
const model = vm.createContext({I18n:i18n});
vm.runInContext(fs.readFileSync(`${__dirname}/../rafa.crypto/Model.js`, 'utf8').replace('.pragma library','').replace('.import "I18n.js" as I18n',''), model);
assert.equal(model.alertDistance({price:105,dir:'above'},100),'faltam 5,00% para o alvo');
assert.equal(model.alertDistance({price:95,dir:'below'},100),'faltam 5,00% para o alvo');
assert.equal(model.alertDistance({price:95,dir:'below'},94),'alvo atingido');
assert.equal(model.alertDistance({price:105,dir:'above'},106),'alvo atingido');
assert.equal(model.alertDistance({price:105,dir:'above'},0),'sem cotação');
const old = [{t:20,c:2},{t:30,c:3}];
const merged = model.mergeCandles(old,[{t:10,c:1},{t:30,c:4}]);
assert.equal(JSON.stringify(merged),JSON.stringify([{t:10,c:1},{t:20,c:2},{t:30,c:4}]));
assert.equal(old[1].c,3);
assert.equal(model.periodStart([{t:0},{t:86400000},{t:172800000}],1),2);
assert.equal(model.periodStart([],30),0);
assert.equal(model.periodInterval(30),'4h');
assert.equal(model.quoteCurrency('binance','usd'),'USDT');
assert.equal(model.quoteCurrency('coingecko','usd'),'US$');
assert.match(model.quoteSource('binance','bitcoin','brl'),/BTC\/BRL.*direto/);
assert.match(model.klinesUrl('BTCBRL','1h',180,1234),/limit=180&endTime=1234$/);
assert.equal(model.chartPair('tether','usd'),null);
console.log('crypto model: alert distances, currencies, history merge and periods passed');
